spring:
  datasource:
    url: jdbc:h2:mem:securitylab;MODE=PostgreSQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    secret-base64: "M3Qyq1m0w9d8t1h8znXlq2l6f3Yq2C8l3m8xZ8S4pTQ="

server:
  port: 8080
